import type { SceneClass } from '../scenes';

import type { City } from './shared-types';

export const THEMES: SceneClass[] = [
  '休閒農業類',
  '其他',
  '古蹟類',
  '國家公園類',
  '國家風景區類',
  '小吃/特產類',
  '廟宇類',
  '文化類',
  '林場類',
  '森林遊樂區類',
  '溫泉類',
  '生態類',
  '自然風景類',
  '藝術類',
  '觀光工廠類',
  '遊憩類',
  '都會公園類',
  '體育健身類',
];

export const CITIES: (City & keyof typeof CityMap)[] = [
  '臺北市',
  '新北市',
  '桃園市',
  '臺中市',
  '臺南市',
  '高雄市',
  '基隆市',
  '新竹市',
  '新竹縣',
  '苗栗縣',
  '彰化縣',
  '南投縣',
  '雲林縣',
  '嘉義縣',
  '嘉義市',
  '屏東縣',
  '宜蘭縣',
  '花蓮縣',
  '臺東縣',
  '金門縣',
  '澎湖縣',
  '連江縣',
];

export const BIKE_CITIES: City[] = [
  '臺北市',
  '新北市',
  '桃園市',
  '臺中市',
  '臺南市',
  '高雄市',
  '基隆市',
  // '新竹市',
  '新竹縣',
  '苗栗縣',
  '彰化縣',
  '南投縣',
  '雲林縣',
  '嘉義縣',
  '嘉義市',
  '屏東縣',
  '宜蘭縣',
  '花蓮縣',
  '臺東縣',
  '金門縣',
  '澎湖縣',
  '連江縣',
];

export const BUS_ESTIMATE_CITIES: City[] = ['桃園市', '臺中市', '高雄市'];

export const MAJOR_CITIES: City[] = [
  '臺北市',
  '新北市',
  '桃園市',
  '臺中市',
  '臺南市',
  '高雄市',
];

export const COUNTIES: City[] = [
  '基隆市',
  '新竹市',
  '新竹縣',
  '苗栗縣',
  '彰化縣',
  '南投縣',
  '雲林縣',
  '嘉義縣',
  '嘉義市',
  '屏東縣',
  '宜蘭縣',
  '花蓮縣',
  '臺東縣',
  '金門縣',
  '澎湖縣',
  '連江縣',
];

export const CityMap = {
  南投縣: 'nantoucounty',
  嘉義市: 'chiayi',
  嘉義縣: 'chiayicounty',
  基隆市: 'keelung',
  宜蘭縣: 'yilancounty',
  屏東縣: 'pingtungcounty',
  彰化縣: 'changhuacounty',
  新北市: 'newtaipei',
  新竹市: 'hsinchu',
  新竹縣: 'hsinchucounty',
  桃園市: 'taoyuan',
  澎湖縣: 'penghucounty',
  臺中市: 'taichung',
  臺北市: 'taipei',
  臺南市: 'tainan',
  臺東縣: 'taitungcounty',
  花蓮縣: 'hualiencounty',
  苗栗縣: 'miaolicounty',
  連江縣: 'lienchiangcounty',
  金門縣: 'kinmencounty',
  雲林縣: 'yunlincounty',
  高雄市: 'kaohsiung',
} as const;

export type CityMap = (typeof CityMap)[keyof typeof CityMap];

export const PTXCityMap = {
  南投縣: 'NantouCounty',
  嘉義市: 'Chiayi',
  嘉義縣: 'ChiayiCounty',
  基隆市: 'Keelung',
  宜蘭縣: 'YilanCounty',
  屏東縣: 'PingtungCounty',
  彰化縣: 'ChanghuaCounty',
  新北市: 'NewTaipei',
  新竹市: 'Hsinchu',
  新竹縣: 'HsinchuCounty',
  桃園市: 'Taoyuan',
  澎湖縣: 'PenghuCounty',
  臺中市: 'Taichung',
  臺北市: 'Taipei',
  臺南市: 'Tainan',
  臺東縣: 'TaitungCounty',
  花蓮縣: 'HualienCounty',
  苗栗縣: 'MiaoliCounty',
  連江縣: 'LienchiangCounty',
  金門縣: 'KinmenCounty',
  雲林縣: 'YunlinCounty',
  高雄市: 'Kaohsiung',
} as const;

export type PTXCityMap = (typeof PTXCityMap)[keyof typeof PTXCityMap];

export const CitySlugMap = {
  changhuacounty: '彰化縣',
  chiayi: '嘉義市',
  chiayicounty: '嘉義縣',
  hsinchu: '新竹市',
  hsinchucounty: '新竹縣',
  hualiencounty: '花蓮縣',
  kaohsiung: '高雄市',
  keelung: '基隆市',
  kinmencounty: '金門縣',
  lienchiangcounty: '連江縣',
  miaolicounty: '苗栗縣',
  nantoucounty: '南投縣',
  newtaipei: '新北市',
  penghucounty: '澎湖縣',
  pingtungcounty: '屏東縣',
  taichung: '臺中市',
  tainan: '臺南市',
  taipei: '臺北市',
  taitungcounty: '臺東縣',
  taoyuan: '桃園市',
  yilancounty: '宜蘭縣',
  yunlincounty: '雲林縣',
} as const;

export type CitySlugMap = (typeof CitySlugMap)[keyof typeof CitySlugMap];

export const CityCodeSlugMap = {
  CHA: 'changhuacounty',
  CYI: 'chiayicounty',
  CYQ: 'chiayicounty',
  HSQ: 'hsinchucounty',
  HSZ: 'hsinchu',
  HUA: 'hualiencounty',
  ILA: 'yilancounty',
  KEE: 'keelung',
  KHH: 'kaohsiung',
  KIN: 'kinmencounty',
  LIE: 'lienchiangcounty',
  MIA: 'miaolicounty',
  NAN: 'nantoucounty',
  NWT: 'newtaipei',
  PEN: 'penghucounty',
  PIF: 'pingtungcounty',
  TAO: 'taoyuan',
  TNN: 'tainan',
  TPE: 'taipei',
  TTT: 'taitungcounty',
  TXG: 'taichung',
  YUN: 'yunlincounty',
} as const;

export type CityCodeSlugMap =
  (typeof CityCodeSlugMap)[keyof typeof CityCodeSlugMap];
