version: 2

updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    groups:
      bun-dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: react
        update-types:
          - version-update:semver-major
      - dependency-name: react-dom
        update-types:
          - version-update:semver-major
      - dependency-name: next
        update-types:
          - version-update:semver-major
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
      - dependency-name: '@types/react'
        update-types:
          - version-update:semver-major
      - dependency-name: '@types/react-dom'
        update-types:
          - version-update:semver-major
      - dependency-name: '@types/node'
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
